backend:
  name: github
  repo: laurence-cmd/mon-site-assistant
  branch: main
  base_url: https://decap-bridge.vercel.app
  auth_endpoint: /oauth/authorize

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Accueil"
        name: "index"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
